# Generated by Django 2.2.5 on 2020-03-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecord',
            name='sign_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courserecord',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '已签到'), (1, '正在签到'), (2, '未开始')], default=2),
        ),
    ]
