# Generated by Django 2.2.5 on 2020-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20200330_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlist',
            name='id_num',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_num',
        ),
        migrations.AlterField(
            model_name='student',
            name='qq',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
