# Generated by Django 2.2.5 on 2020-04-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20200330_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserecord',
            name='sign_date',
        ),
        migrations.AddField(
            model_name='classlist',
            name='course_end_time',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classlist',
            name='sign_end_time',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signrecord',
            name='attendance',
            field=models.SmallIntegerField(choices=[(0, '已签到'), (1, '迟到'), (2, '早退'), (3, '缺勤')], default=3),
        ),
    ]
