# Generated by Django 2.2.5 on 2020-04-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20200403_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecord',
            name='start_sign_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
