# Generated by Django 2.2.5 on 2020-04-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_courserecord_start_sign_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='student_num',
            field=models.CharField(blank=True, help_text='请用真实学号(工号)', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='crm.Tag'),
        ),
    ]
